name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Creating dep.txt
      run: |
        date > dep.txt
        cat dep.txt

    - name: Gn gen
      run: ./gn-linux gen out

    - name: First build (triggers the action - expected)
      run: |
        ./ninja-linux -C out write-zip
        cat out/obj/output.zip

    - name: Second build (does not trigger the action - expected)
      run: |
        ./ninja-linux -C out write-zip
        cat out/obj/output.zip

    - name: Modify dep.txt
      run: |
        cat dep.txt
        sleep 1
        date > dep.txt
        cat dep.txt

    - name: Third build (does not trigger the action; only runs a stamp - unexpected)
      run: |
        ./ninja-linux -C out write-zip
        cat out/obj/output.zip
