name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Creating dep.txt
      run: |
        date > dep.txt
        cat dep.txt

    - name: Gn gen
      run: PATH="depot_tools:$PATH" gn gen out

    - name: First build (triggers the action)
      run: |
        PATH="depot_tools:$PATH" ninja -C out myaction
        cat out/obj/output.txt

    - name: Second build (does not trigger the action)
      run: |
        PATH="depot_tools:$PATH" ninja -C out myaction
        cat out/obj/output.txt

    - name: Modify dep.txt
      run: |
        cat dep.txt
        date > dep.txt
        cat dep.txt

    - name: Third build (does not trigger the action; only runs a stamp)
      run: |
        PATH="depot_tools:$PATH" ninja -C out myaction
        cat out/obj/output.txt
